apiVersion: v1
kind: Service
metadata:
  name: jurimetria-ml
  labels:
    app: jurimetria-ml
spec:
  type: ClusterIP
  selector:
    app: jurimetria-ml
  ports:
    - name: http
      port: 80
      targetPort: http
